### ISSUE TITLE
Incorrect function description in TMP117 methods

### ISSUE THREAD

**Issue by julia-claxton** [GLEE2023/GLEE2023#21]
File path: GLEE2023/src/TMP117.cpp (https://github.com/GLEE2023/GLEE2023/blob/prod/src/TMP117.cpp)
Line 180-181

The description for the `read2Byte` function reads "This function returns the I2C address of the temperature sensor." This doesn't appear to be correct, from what I can gather the function is used to read data from a given register on the TMP117.

**Comment by luke-ro** [comment]
Thanks for catching that. Should be fixed now. "Returns 2 bytes of data located at registerAddress"
